spring:
  application:
    name: eureka-server
  profiles:
    active: stage


---
spring:
  config:
    activate:
      on-profile: localhost
    import: configserver:
  # cloud:
  #   config:
  #     uri: http://localhost:8888

info:
  component: Eureka Server - Github - Localhost

eureka:
  instance:
    appname: eureka-server
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
  port: 8763

---
spring:
  config:
    activate:
      on-profile: stage
    import: configserver:

  # cloud:
  #   config:
  #     uri: http://config-server:8888

info:
  component: Eureka Server - Github - Stage

server:
  port: 8765

eureka:
  instance:
    appname: eureka-server
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
